name: Deploy to AWS EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, curl, gd, intl, mysqlnd, pdo, zip

      - name: Install Node dependencies
        run: npm install

      - name: Build assets locally
        run: npm run build

      - name: Save SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Sync files to EC2 with rsync
        run: |
          rsync -avz --exclude='.env' --exclude='storage' --exclude='vendor' --delete ./ deploy@16.79.30.150:/var/webapps/finvise-assesment/
        env:
          RSYNC_RSH: "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no"

      - name: Finalize deployment on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: 16.79.30.150
          username: deploy
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd /var/webapps/finvise-assesment
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
