name: Deploy to AWS EC2

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, curl, gd, intl, mysqlnd, pdo, zip

      - name: Install Node dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@v1
        with:
          host: 16.79.30.150
          username: deploy
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: .
          target: /var/webapps/finvise-assesment

      - name: Execute deployment script
        uses: appleboy/ssh-action@v1
        with:
          host: 16.79.30.150
          username: deploy
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            rsync -avz --exclude=".env" --exclude="storage" --exclude="vendor" ./ /var/webapps/finvise-assesment
            cd /var/webapps/finvise-assesment
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
