name: Deploy to AWS EC2

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, curl, gd, intl, mysqlnd, pdo, zip

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Clear cache
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      - name: Deploy to EC2
        uses: appleboy/scp@master
        with:
          host: 16.79.30.150
          username: deploy
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: .
          target: /var/www/finvise-assesment # /var/www/finvise-assesment

      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: 16.79.30.150
          username: deploy
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd /var/www/finvise-assesment
            composer install
            npm run build
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
